### PR TITLE
Modifications for use in runtimecore 

### PR DESCRIPTION
**Pull request by ghost**
The following are included:

Include output from generated code. 
- This loads OGL versions 3.3-4.5 and GLES versions 2-3.2

Modify for use in RTC
- The function that loads GLES (versions 2.0 and up) was changed to accept an additional function, which is used to load extension functions (instead of using the same function to do both).
- A lua file what created to build the solution

### CODE REVIEW

**Comment by ghost** [comment]
@chri7325 Can you have a look at the lua file? We actually only want this for our ANGLE build, so I can remove the other platforms if that's how it should work.

**Comment by chri7325** [comment]
@teburt I wouldn't worry about deleting unused platforms. If we need this later, we won't have to bother putting them in. The main 3rdparty lua will only invoke this project for angle so we won't be building it on others. Is the output directory controllable? Can we add the files to the root so we don't have to play with include paths?

**Comment by ghost** [comment]
> Is the output directory controllable? Can we add the files to the root so we don't have to play with include paths?

Yes, we can put it wherever - just would prefer to have it in a folder so it's clear we've added something that's not part of the tool itself.

I did update the lua files so the header can be included - is there anything else from the project included by default we want to turn off?

**Comment by chri7325** [comment]
Well we would need to update the global lua files so that folder will be in the include path. That's what I was referring too. I guess we'd only need it for Windows lua files

**Comment by ghost** [comment]
Ok, I see. Eventually would be the rest of the platforms. I guess we don't need a special folder - this is our runtimecore branch, and there won't be a lot of activity here anyway. 

I'll move it to 'src' and 'include' under the root if that works.

**Comment by chri7325** [comment]
@teburt the final thing would be to add the header to the pure root.  Alternatively, we could leave the header where it is and add the include path just to HAL and any low level test apps.  The root would mean no modifications to any build files and puts it in line with our other c libraries which just have everything at the root.  I see pros and cons to both so I'll leave that up to you since you own this repo.

**Comment by ghost** [comment]
Sounds good, I'll keep it in line with the rest of the repos then

**Comment by ghost** [comment]
@chri7325 is this good to go?

**Comment by chri7325** [comment]
👍

**Pull request merged**
